<h1>Blog Sample (MVC) with NO framework using</h1>
<div class="row">

    <div class="col-md-8">


        www.check24.de
        
        <h2>Specifications for the sample working</h2>
        <p>Dear candidate,</p>
        <p>on the following pages you will find the specifications for the sample work. When the application is a</p>
        <p>simple blog.</p>
        <p>We want to get an insight into your style, your approach and your skills.</p>
        <p>Please note the following:</p>
        <p>• It does not use a framework / no MVC frameworks are allowed</p>
        <p>• Smaller libraries such as Smarty or jQuery may be used</p>
        <p>• You have a total of 5 hours for the application available</p>
        <p>• The estimated amount of work exceeds the processing time of 5 hours willingly. Work concentrated</p>
        <p>and quickly (on average about 80% of applicants provide application ready to ask)</p>
        <p>• If you have completed parts of the application, test it on operability and accuracy</p>
        <p>• The application must be implemented object-oriented and have a clean structure</p>
        <p>• If you have questions or problems please do not hesitate to talk to your partner. The aim is to produce</p>
        <p>as much good working code in 5 hours.</p>
        <p>• Ensure that your implementation is not basically focused on the implementation of a "mini-framework"</p>
        <p>but in the creation of structures. The major aim is the creation of a blog in object-oriented manner, at</p>
        <p>the highest possible level.</p>
        <p>For questions about technical specifications please contact your contact person at any time.</p>
        <p>Good luck and thank you for your time and your interest!</p>
        <p>CHECK24</p>
        <p>─</p>
        <p>─</p>
        <p>─</p>
        <p>Seite 2/5</p>
        <p>The basic functions of a blog you are no doubt aware. On this basic understanding, we build on.</p>
        <p>1.1. Database and data model</p>
        <p>All data are to be stored in the allocated MySQL database. The Relational Data Model for you need to</p>
        <p>create on the basis of requirements. Maintain a structured naming. All identifiers (eg, tables, fields,</p>
        <p>variables) and the documentation must be drawn up in English.</p>
        <p>1.2 Extent of development</p>
        <p>Normally, programs divided into a front-end to (the "visible" blog) and a backend (administration of the</p>
        <p>system). In this simple blog there is only one front-end area. A separate administration interface and a</p>
        <p>user documentation is not to create. Only the source code is shall be documented inline (in important</p>
        <p>places such as solutions of extensions also detail).</p>
        <p>Certain areas are designated as 'extension', edit this only if you have implemented other functions. Note</p>
        <p>that you do not time to deal with the basic functions, you do not pay attention to fight on several fronts.</p>
        <p>The create parts should be accurate and complete. Create all extensions you can and attach your own</p>
        <p>extensions. You can write the specification notes everywhere.</p>
        <p>1.3 Checklist</p>
        <p>So that we know what parts you have edited, you will find a checklist here. Highlight completely finished</p>
        <p>and functioning parts accordingly. Also for partially finished parts, there is a range.</p>
        <p>Nr. Area partly completely</p>
        <p>2.1 surface</p>
        <p>2.2 Home page</p>
        <p>2.3 Detail page</p>
        <p>2.3.E1 Extension Spam</p>
        <p>2.4 Login</p>
        <p>2.5 Logout</p>
        <p>2.6 Add entry</p>
        <p>2.6.E1 Extension Rich Text Editor</p>
        <p>2.6.E2 Extension Editing of entries</p>
        <p>2.7 Imprint</p>
        <p>Your Extensions</p>
        <p>Seite 3/5</p>
        <p>2. frontend area</p>
        <p>2.1 Surface</p>
        <p>The surface is relatively simple. Structurally, you can follow the known blog sites. It follows a small</p>
        <p>scheme:</p>
        <p>Above is space for the blog header (a graphic or banner). Below this is the menu bar link to the</p>
        <p>corresponding pages. In the middle are the content (more on that later). In Footer is just a link to the</p>
        <p>Contacts page. "Add Entry" and "Logout" will appear only after a successful login.</p>
        <p>2.2 Home page</p>
        <p>The home is also the overview page with all entries, ie once you get to the page, the first 3 entries</p>
        <p>appear. About the same page, you can scroll to older entries (Sort Descending by date, ie newest listed</p>
        <p>first):</p>
        <p>[....]</p>
        <p>The entries appear with:</p>
        <p> Date (German Format if date today then instead of Date "Today")</p>
        <p>Space for image (links to home-page)</p>
        <p>Home-page - Login – [Add entry] - [Logout]</p>
        <p>Content</p>
        <p>© 2015 - Imprint</p>
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam</p>
        <p>nonummy nibh euismod tincidunt ut laoreet dolore.... [lesen]</p>
        <p>Heute: Titel 1</p>
        <p>Autor: $name %anzahl% Kommentare</p>
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam</p>
        <p>nonummy nibh euismod tincidunt ut laoreet dolore.</p>
        <p>01.05.2006: Titel 3</p>
        <p>Autor: $name $anzahl Kommentare</p>
        <p>Zu den älteren Einträgen</p>
        <p>Seite 4/5</p>
        <p> Title</p>
        <p> Text (wrapped accordingly, if more than 1000 characters, with "..." completed)</p>
        <p> author (the author's name, just the login name)</p>
        <p> Comments (Number of comments to the article)</p>
        <p>After the third entry of the link appears to go to the previous page. If there are no previous records of</p>
        <p>more link no longer appears.</p>
        <p>The entry is linked as follows:</p>
        <p> Title, number of comments (number and text): This links to the detail page</p>
        <p> Author: Displays only entries of the author and link to the first page. The logic is the same, but</p>
        <p>just Entries an author are displayed.</p>
        <p>Otherwise, there are on the summary page no further functions.</p>
        <p>2.3 Detail page</p>
        <p>The entry will be fully displayed, otherwise the display of the entry is unchanged. The links are also</p>
        <p>completely identical:</p>
        <p>In addition: In the entry All comments appear to entry, numbered (starts at 1 and runs continuously on,</p>
        <p>so: 2, 3, 4, 5). A Paging is not required, it can be displayed directly all Comments.</p>
        <p>If one is currently logged in as a valid user, the IP of the entry appears after the time. In addition to the</p>
        <p>title of the entry will "delete" (only if you created the entry). Clicking on Delete, will see a Javascript YES</p>
        <p>/ NO query Choose Yes, the entry including all comments will be deleted.</p>
        <p>At the very end there is a form for entering a comment the following entry:</p>
        <p>[....Entry as to Home...]</p>
        <p>1 comment yet:</p>
        <p>1. Max (link to the URL you entered) said: (06.10.2006 12:34):</p>
        <p>I think the record is very good, keep it up!</p>
        <p>Leave a comment:</p>
        <p>Name</p>
        <p>Mail (optional)</p>
        <p>URL (optional)</p>
        <p>remark</p>
        <p>Send</p>
        <p>Seite 5/5</p>
        <p>When you enter the name and comment required. Missing an entry or appear valid (syntactically wrong),</p>
        <p>the form is reloaded with an error. Remain inputs. In addition, the comment IP address is detected. Once</p>
        <p>the comment has been detected in the comment under the entry appears.</p>
        <p>With each comment the author receives all the information of the comment in an informal e-mail, the</p>
        <p>subject line: "Comment by Max to: $ title".</p>
        <p>Expansion 1: Perhaps you have an idea of how to protect the blog from comment spam, so no automated</p>
        <p>or not too many comments can be made.</p>
        <p>2.4 Login</p>
        <p>Users can log in via a link, this login name and password will be requested. In existence for the user is</p>
        <p>a valid entry in the database, the user is logged in and redirected to the home page. If you logged in will</p>
        <p>see two additional menu links: "Logout" and "Add Entry". The menu item "Login" disappears.</p>
        <p>Notice: A form for registering of members is not required (you wear this manually)!</p>
        <p>2.5 Logout</p>
        <p>It is only performed a logout. The "internal" links "Add Entry" and disappear "Logout", you land directly</p>
        <p>on the homepage.</p>
        <p>2.6 Add Eintrag</p>
        <p>Here, a new entry will be added. The new entry is assigned to the user who is currently logged on,</p>
        <p>another assignment is not allowed. So queried only date, title, and a text description. Following the</p>
        <p>successful insertion of an entry you will be forwarded directly to the detail page of the entry. You will</p>
        <p>immediately appear on the home page (corresponding to the date). The date is before filled with the</p>
        <p>date of today.</p>
        <p>For this form, there is no default. Shape it according to the requirements of a real "blog writer".</p>
        <p>Expansion 1: Take a publicly accessible Rich Text Library so you can also make the text bold (eg</p>
        <p>TinyMCE).</p>
        <p>Extension 2: Expand the Detail Page in addition to the "Delete link" with an "Edit Link", which invites</p>
        <p>the entry and (remain only title and content, date and author unchanged) for processing permits. One</p>
        <p>may of course only deal with his own messages.</p>
        <p>2.7 Imprint</p>
        <p>The imprint is a static page and can eg be filled with your data.</p>
        <p>Expansion 1: Get started data from the database and list their contact details on (login name, full name,</p>
        <p>street, postcode, place). So all authors appear in Contacts.</p>

    </div>
</div>