<h1>Please login to add new post</h1>
<div class="row">

    <div class="col-md-8">


        For the test sake input login <b>eugene.kaurov@gmail.com</b> and password <b>123</b>
        <?php
        if (isset($_REQUEST['error']) AND $_REQUEST['error']) echo "<br /><q style='color:red'>Credentials are incorrect</q>";



        /*



        <form name="loginform" id="loginform" action="/?action=loginsubmitted" method="post">
            <p>
                <label for="user_login">Email<br>
                    <input type="email" name="email" id="user_login" aria-describedby="login_error" class="input" value="" size="20"></label>
            </p>
            <p>
                <label for="user_pass">Password<br>
                    <input type="password" name="password" id="user_pass" aria-describedby="login_error" class="input" value="" size="20"></label>
            </p>
            <p class="submit">
                <input type="submit" name="wp-submit" id="wp-submit" class="btn btn-default" value="Login">


            </p>
        </form>

        */
        ?>



        <form class="form-horizontal" action="/?action=loginsubmitted" method="post">
            <div class="form-group">
                <label class="control-label col-sm-2" for="email">Email:</label>
                <div class="col-sm-10">
                    <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="password">Password:</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" id="password" name="password" placeholder="Enter password">
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">Submit</button>
                </div>
            </div>
        </form>




    </div>
</div>