<h1>Blog Posts</h1>
<div class="row">

    <div class="col-md-8">

        <?php
        $is_mini_mode = true;
        $escapeHtml = 'htmlspecialchars';
        $posts = $variables;
                
        foreach ($posts as $postArray)
        {
            if ($is_mini_mode)
            {
                ?>
                <h3>
                    <a href="/?action=post&id=<?= $postArray['id'] ?>">
                        <?= $escapeHtml($postArray['title']); ?>
                    </a>    
                </h3>
                <?php
            } else
            {
                echo '<h1>' . $escapeHtml($postArray['title']) . '</h1>';
            }
            ?>
            <div class="content">
                <?= $escapeHtml($postArray['content']);
            ?>
            </div>
            <p>
                Author: <?php
                echo $escapeHtml($postArray['author']);
                
                echo $is_mini_mode ? " | " : "<br />";
                ?>
                Published: <?php echo $escapeHtml(date('jS \of F Y', strtotime($postArray['date_created']))); 
                
                echo $is_mini_mode ? " | " : "<br />";
                ?> 
                Tags: <?= $escapeHtml($postArray['tags']); ?>   
            </p> 
            <?php
            echo $is_mini_mode ? "<hr />" : "";
        }
        ?>

    </div>
</div>