<div class="row">

    <div class="col-md-8">

        <?php
        $is_mini_mode = false;
        $escapeHtml = 'htmlspecialchars';
        $postArray = $variables;
                
        if ($postArray)
        {
            if ($is_mini_mode)
            {
                ?>
                <h3>
                    <a href="/?action=post&id=<?= $postArray['id'] ?>">
                        <?= $escapeHtml($postArray['title']); ?>
                    </a>    
                </h3>
                <?php
            } else
            {
                echo '<h1>' . $escapeHtml($postArray['title']) . '</h1>';
            }
            ?>
            <div class="content">
                <?= $escapeHtml($postArray['content']);
            ?>
            </div>
            <p>
                Author: <?php
                echo $escapeHtml($postArray['author']);
                
                echo $is_mini_mode ? " | " : "<br />";
                ?>
                Published: <?php echo $escapeHtml(date('jS \of F Y', strtotime($postArray['date_created']))); 
                
                echo $is_mini_mode ? " | " : "<br />";
                
                
                if(!$is_mini_mode && $postArray['comment'] )
                {
                    echo "<h3>Comments:</h3>";
                    foreach ($postArray['comment'] as $key => $row) 
                    {
                        echo "
                        <h4>{$row['content']}</h4>
                        {$row['author']} on  
                        {$row['date_created']}";
                        echo "<hr />";
                    }
                    
                    /*
                    ?>
                    <h3>Add Comment</h3>
                    <form action="/?action=addpostsubmitted" class="form-horizontal"  method="post">
                      <div class="form-group">
                        <label class="control-label col-sm-2" for="title">Title:</label>
                        <div class="col-sm-10">
                          <input type="text" class="form-control" id="title" name="title" placeholder="Enter Title">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-sm-2" for="content">Content:</label>
                        <div class="col-sm-10"> 
                          <textarea class="form-control" id="content" name="content" width="120"></textarea>
                        </div>
                      </div>


                      <div class="form-group"> 
                        <div class="col-sm-offset-2 col-sm-10">
                          <button type="submit" class="btn btn-default">Submit</button>
                        </div>
                      </div>
                    </form>
                    <?php  
                    */      
                            
                }
                ?>   
            </p> 
            <?php
            echo $is_mini_mode ? "<hr />" : "";
        }
        ?>

    </div>
</div>